name: PowerShell script
author: Amadevus
description: >
  Run PowerShell scripts within a hydrated context,
  with workflow-command cmdlets; inspired by actions/github-script.
inputs:
  script:
    description: PowerShell script to execute in Actions-hydrated context
    required: true
outputs:
  result:
    description: Return value of script execution
    value: ${{ steps.script.outputs.result }}
  error:
    description: Exception details, if any was thrown during script execution.
    value: ${{ steps.script.outputs.error }}
runs:
  using: composite
  steps:
    - id: get_script
      shell: pwsh
      run: |
        if (Test-Path ${{ inputs.script }}) {
          $script = Get-Content ${{ inputs.script }} -Raw
        } 
        else {
          $script = ${{ inputs.script }}
        }
        echo "SCRIPT_CONTENT=$script" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        
    - run: ${{ github.action_path }}/action.ps1
      id: script
      shell: pwsh
      env:
        TEMP: ${{ runner.temp }}
        PWSH_SCRIPT_ACTION_TEXT: ${{ env.SCRIPT_CONTENT }}
        PWSH_SCRIPT_ACTION_GITHUB: ${{ toJson(github) }}
        PWSH_SCRIPT_ACTION_JOB: ${{ toJson(job) }}
        PWSH_SCRIPT_ACTION_RUNNER: ${{ toJson(runner) }}
        PWSH_SCRIPT_ACTION_STRATEGY: ${{ toJson(strategy) }}
        PWSH_SCRIPT_ACTION_MATRIX: ${{ toJson(matrix) }}
branding:
  icon: terminal
  color: blue
